/* 1. Count the customers with grades above Bangalore’s average. */

SELECT GRADE, COUNT (CUSTOMER_ID) FROM CUSTOMER GROUP BY GRADE HAVING GRADE > (SELECT AVG(GRADE) FROM CUSTOMER WHERE CITY='BANGALORE');

  /* OR*/

SELECT COUNT(*) FROM CUSTOMER WHERE GRADE >= (SELECT AVG(GRADE) FROM CUSTOMER WHERE CITY='BANGALORE');