/* 2. Find the name and numbers of all salesmen who had more than one customer. */

SELECT SALESMAN_ID, NAME
FROM SALESMAN A
WHERE 1 < (SELECT COUNT (*)
			FROM CUSTOMER
			WHERE SALESMAN_ID=A.SALESMAN_ID);
            /*  OR*/
SELECT NAME,SALESMAN_ID FROM SALESMAN WHERE SALESMAN_ID = ANY(
	SELECT SALESMAN_ID FROM CUSTOMER GROUP BY (SALESMAN_ID) HAVING COUNT(SALESMAN_ID) >1 );
