/* 3. List all salesmen and indicate those who have and don’t have customers in their cities (Use UNION operation.) */

SELECT SALESMAN.SALESMAN_ID, NAME, 'HAVE CUSTOMER IN CITY' AS HAVE_CUSTOMER_IN_CITY FROM SALESMAN, CUSTOMER WHERE SALESMAN.CITY = CUSTOMER.CITY
UNION
SELECT SALESMAN_ID, NAME, 'HAVE NO CUSTOMER IN CITY'AS HAVE_CUSTOMER_IN_CITY FROM SALESMAN WHERE NOT SALESMAN.CITY IN (SELECT CUSTOMER.CITY FROM CUSTOMER) 
ORDER by SALESMAN_ID;